# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
